export const robots = [
  {
    id: 1,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
  },
  {
    id: 2,
    name: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
  },
  {
    id: 3,
    name: 'Hossam Omar',
    username: 'Samantha',
    email: 'hossam@yesenia.net',
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
  },
  {
    id: 7,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
  },
  {
    id: 9,
    name: 'Manal Omar',
    username: 'Delphine',
    email: 'manal_omar@dana.io',
  },
  {
    id: 10,
    name: 'Essam Mohammed',
    username: 'Moriah.Stanton',
    email: 'essam.moh32@karina.biz',
  },
  {
    id: 11,
    name: 'Ralf Elzoger',
    username: 'Ralf.Z',
    email: 'Ralf.Zoger55@karina.biz',
  },
  {
    id: 12,
    name: 'Ralf Elzoger',
    username: 'Ralf.Z',
    email: 'Ralf.Zoger55@karina.biz',
  },
  {
    id: 13,
    name: 'Alla Muhammed',
    username: 'Ralf.Z',
    email: 'alla.mohammed@karina.biz',
  },
  {
    id: 14,
    name: 'Mohammed Omar',
    username: 'Ralf.Z',
    email: 'mohammed.omar55@karina.biz',
  },
  {
    id: 15,
    name: 'Mo3az Omar',
    username: 'Ralf.Z',
    email: 'moaaz.omar@karina.biz',
  },
  {
    id: 16,
    name: 'Ralf Elzoger',
    username: 'Ralf.Z',
    email: 'Ralf.Zoger55@karina.biz',
  },
  {
    id: 17,
    name: 'Ralf Elzoger',
    username: 'Ralf.Z',
    email: 'Ralf.Zoger55@karina.biz',
  },
  {
    id: 18,
    name: 'Alla Muhammed',
    username: 'Ralf.Z',
    email: 'alla.mohammed@karina.biz',
  },
  {
    id: 19,
    name: 'Mohammed Omar',
    username: 'Ralf.Z',
    email: 'mohammed.omar55@karina.biz',
  },
  {
    id: 20,
    name: 'Mo3az Omar',
    username: 'Ralf.Z',
    email: 'moaaz.omar@karina.biz',
  },
  {
    id: 21,
    name: 'alla mohammed',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
  },
  {
    id: 22,
    name: 'moaz omar',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
  },
  {
    id: 23,
    name: 'mohammed omar',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
  },
  {
    id: 24,
    name: 'Manal Omar',
    username: 'Delphine',
    email: 'manal_omar@dana.io',
  },
  {
    id: 25,
    name: 'Essam Mohammed',
    username: 'Moriah.Stanton',
    email: 'essam.moh32@karina.biz',
  },
];
